// Code generated by Kitex v0.11.3. DO NOT EDIT.

package trainingservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	training "github.com/cylScripter/openapi/training"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ImportInternship": kitex.NewMethodInfo(
		importInternshipHandler,
		newTrainingserviceImportInternshipArgs,
		newTrainingserviceImportInternshipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	trainingserviceServiceInfo                = NewServiceInfo()
	trainingserviceServiceInfoForClient       = NewServiceInfoForClient()
	trainingserviceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return trainingserviceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return trainingserviceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return trainingserviceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "trainingservice"
	handlerType := (*training.Trainingservice)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "training",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func importInternshipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*training.TrainingserviceImportInternshipArgs)
	realResult := result.(*training.TrainingserviceImportInternshipResult)
	success, err := handler.(training.Trainingservice).ImportInternship(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTrainingserviceImportInternshipArgs() interface{} {
	return training.NewTrainingserviceImportInternshipArgs()
}

func newTrainingserviceImportInternshipResult() interface{} {
	return training.NewTrainingserviceImportInternshipResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ImportInternship(ctx context.Context, req *training.ImportInternshipReq) (r *training.ImportInternshipResp, err error) {
	var _args training.TrainingserviceImportInternshipArgs
	_args.Req = req
	var _result training.TrainingserviceImportInternshipResult
	if err = p.c.Call(ctx, "ImportInternship", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
